### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by takuhiro-4** [takuhiro-4/protospace-33961#1]
#URL
https://protospace-33961.herokuapp.com

**Comment by natsuki1031** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所が1点ございました。
以下のご確認をお願いします！

[修正依頼箇所]
◯ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、
ログインページにリダイレクトされるようにしましょう
→現在トップページにリダイレクトされてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by natsuki1031** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、先ほどお伝えした修正点が修正できていないようでした。
デプロイを含め、以下のご確認をお願いします！

[修正依頼箇所]
◯ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、
ログインページにリダイレクトされるようにしましょう
→現在トップページにリダイレクトされてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by MasaakiTanabashi** [comment]
takuhiro-4さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◎ユーザーの新規登録ができません。
（先程指摘させていただいた点は、修正できております。）

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takuhiro-4** [comment]
一番上のURLから入りましたが、新規登録はできました。
下記はギャゾーの動画です
https://gyazo.com/a499a7c3a37c6dc3c86a629653944f56

トップページの新規登録から行いましたが、どこを直せばいいかわからないので、もう一度確認いただくことはできますでしょうか？

**Comment by MasaakiTanabashi** [comment]
takuhiro-4さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
（登録に使用しようとしていたメールアドレスがすでに使用されていた可能性がございます。お手数をおかけし申し訳ございませんでした。）

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
